// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {terminal} from '../models';
import {inventory} from '../models';
import {codex} from '../models';
import {docker} from '../models';
import {session} from '../models';
import {profile} from '../models';

export function AttachSession(arg1:string):Promise<void>;

export function AttachSessionWithTerminal(arg1:string,arg2:string):Promise<void>;

export function CreateSession(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CreateSessionWithOptions(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string):Promise<void>;

export function DeleteCodexConfig(arg1:string):Promise<void>;

export function DeleteDockerConfig(arg1:string):Promise<void>;

export function DeleteHost(arg1:string):Promise<void>;

export function DeleteHostGroup(arg1:string):Promise<void>;

export function DeleteProfile(arg1:string):Promise<void>;

export function ExportBurrow():Promise<string>;

export function GetCodexConfigToml(arg1:string):Promise<string>;

export function GetDefaultTerminal():Promise<string>;

export function GetInstalledTerminals():Promise<Array<terminal.TerminalApp>>;

export function GetInventory():Promise<inventory.Inventory>;

export function ImportBurrow(arg1:string):Promise<void>;

export function KillSession(arg1:string):Promise<void>;

export function ListCodexConfigs():Promise<Array<codex.Config>>;

export function ListDockerConfigs():Promise<Array<docker.Config>>;

export function ListLaunchPlugins():Promise<Array<session.PluginInfo>>;

export function ListProfiles():Promise<Array<profile.Profile>>;

export function ListSessions():Promise<Array<session.SessionStatus>>;

export function RestartSession(arg1:string):Promise<void>;

export function SaveCodexConfig(arg1:codex.SaveRequest):Promise<codex.Config>;

export function SaveDockerConfig(arg1:docker.SaveRequest):Promise<docker.Config>;

export function SaveHost(arg1:inventory.Host):Promise<void>;

export function SaveHostGroup(arg1:inventory.HostGroup):Promise<void>;

export function SaveInventory(arg1:inventory.Inventory):Promise<void>;

export function SaveInventoryDefaults(arg1:inventory.HostDefaults):Promise<void>;

export function SaveProfile(arg1:profile.Profile,arg2:Record<string, string>):Promise<void>;

export function SetDefaultTerminal(arg1:string):Promise<void>;

export function UpdateSession(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateSessionWithOptions(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string):Promise<void>;
