// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {terminal} from '../models';
import {profile} from '../models';
import {session} from '../models';

export function AttachSession(arg1:string):Promise<void>;

export function AttachSessionWithTerminal(arg1:string,arg2:string):Promise<void>;

export function CreateSession(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteProfile(arg1:string):Promise<void>;

export function GetDefaultTerminal():Promise<string>;

export function GetInstalledTerminals():Promise<Array<terminal.TerminalApp>>;

export function KillSession(arg1:string):Promise<void>;

export function ListProfiles():Promise<Array<profile.Profile>>;

export function ListSessions():Promise<Array<session.SessionStatus>>;

export function SaveProfile(arg1:profile.Profile,arg2:Record<string, string>):Promise<void>;

export function SetDefaultTerminal(arg1:string):Promise<void>;

export function UpdateSession(arg1:string,arg2:string,arg3:string):Promise<void>;
