// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AttachSession(arg1) {
  return window['go']['main']['App']['AttachSession'](arg1);
}

export function AttachSessionWithTerminal(arg1, arg2) {
  return window['go']['main']['App']['AttachSessionWithTerminal'](arg1, arg2);
}

export function CreateSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateSession'](arg1, arg2, arg3);
}

export function CreateSessionWithOptions(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['CreateSessionWithOptions'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function CreateSessionWithOptionsV2(arg1) {
  return window['go']['main']['App']['CreateSessionWithOptionsV2'](arg1);
}

export function DeleteCodexConfig(arg1) {
  return window['go']['main']['App']['DeleteCodexConfig'](arg1);
}

export function DeleteDockerConfig(arg1) {
  return window['go']['main']['App']['DeleteDockerConfig'](arg1);
}

export function DeleteHost(arg1) {
  return window['go']['main']['App']['DeleteHost'](arg1);
}

export function DeleteHostGroup(arg1) {
  return window['go']['main']['App']['DeleteHostGroup'](arg1);
}

export function DeletePluginConfig(arg1) {
  return window['go']['main']['App']['DeletePluginConfig'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function DeleteScriptConfig(arg1) {
  return window['go']['main']['App']['DeleteScriptConfig'](arg1);
}

export function DetachSession(arg1) {
  return window['go']['main']['App']['DetachSession'](arg1);
}

export function ExportBurrow() {
  return window['go']['main']['App']['ExportBurrow']();
}

export function GetCodexConfigToml(arg1) {
  return window['go']['main']['App']['GetCodexConfigToml'](arg1);
}

export function GetDefaultTerminal() {
  return window['go']['main']['App']['GetDefaultTerminal']();
}

export function GetDenOrder(arg1) {
  return window['go']['main']['App']['GetDenOrder'](arg1);
}

export function GetInstalledTerminals() {
  return window['go']['main']['App']['GetInstalledTerminals']();
}

export function GetInventory() {
  return window['go']['main']['App']['GetInventory']();
}

export function GetProviderPresets() {
  return window['go']['main']['App']['GetProviderPresets']();
}

export function ImportBurrow(arg1) {
  return window['go']['main']['App']['ImportBurrow'](arg1);
}

export function ImportSSHConfig(arg1) {
  return window['go']['main']['App']['ImportSSHConfig'](arg1);
}

export function KillSession(arg1) {
  return window['go']['main']['App']['KillSession'](arg1);
}

export function ListCodexConfigs() {
  return window['go']['main']['App']['ListCodexConfigs']();
}

export function ListDockerConfigs() {
  return window['go']['main']['App']['ListDockerConfigs']();
}

export function ListLaunchPlugins() {
  return window['go']['main']['App']['ListLaunchPlugins']();
}

export function ListPluginConfigs(arg1) {
  return window['go']['main']['App']['ListPluginConfigs'](arg1);
}

export function ListProfiles() {
  return window['go']['main']['App']['ListProfiles']();
}

export function ListScriptConfigs() {
  return window['go']['main']['App']['ListScriptConfigs']();
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function OpenDen(arg1) {
  return window['go']['main']['App']['OpenDen'](arg1);
}

export function PickDirectory(arg1) {
  return window['go']['main']['App']['PickDirectory'](arg1);
}

export function PreviewSSHConfigImport(arg1) {
  return window['go']['main']['App']['PreviewSSHConfigImport'](arg1);
}

export function RestartSession(arg1) {
  return window['go']['main']['App']['RestartSession'](arg1);
}

export function SaveCodexConfig(arg1) {
  return window['go']['main']['App']['SaveCodexConfig'](arg1);
}

export function SaveDenOrder(arg1, arg2) {
  return window['go']['main']['App']['SaveDenOrder'](arg1, arg2);
}

export function SaveDockerConfig(arg1) {
  return window['go']['main']['App']['SaveDockerConfig'](arg1);
}

export function SaveHost(arg1) {
  return window['go']['main']['App']['SaveHost'](arg1);
}

export function SaveHostGroup(arg1) {
  return window['go']['main']['App']['SaveHostGroup'](arg1);
}

export function SaveInventory(arg1) {
  return window['go']['main']['App']['SaveInventory'](arg1);
}

export function SaveInventoryDefaults(arg1) {
  return window['go']['main']['App']['SaveInventoryDefaults'](arg1);
}

export function SavePluginConfig(arg1) {
  return window['go']['main']['App']['SavePluginConfig'](arg1);
}

export function SaveProfile(arg1, arg2) {
  return window['go']['main']['App']['SaveProfile'](arg1, arg2);
}

export function SaveScriptConfig(arg1) {
  return window['go']['main']['App']['SaveScriptConfig'](arg1);
}

export function SetDefaultTerminal(arg1) {
  return window['go']['main']['App']['SetDefaultTerminal'](arg1);
}

export function TestScriptCommand(arg1) {
  return window['go']['main']['App']['TestScriptCommand'](arg1);
}

export function UpdateSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateSession'](arg1, arg2, arg3);
}

export function UpdateSessionWithOptions(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['UpdateSessionWithOptions'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function UpdateSessionWithOptionsV2(arg1) {
  return window['go']['main']['App']['UpdateSessionWithOptionsV2'](arg1);
}
