// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {inventory} from '../models';
import {session} from '../models';
import {main} from '../models';
import {terminal} from '../models';
import {provider} from '../models';
import {workspace} from '../models';
import {codex} from '../models';
import {docker} from '../models';
import {integration} from '../models';
import {pluginconfig} from '../models';
import {profile} from '../models';
import {scriptcfg} from '../models';

export function AttachSession(arg1:string):Promise<boolean>;

export function AttachSessionWithTerminal(arg1:string,arg2:string):Promise<boolean>;

export function CheckHostHealth(arg1:string):Promise<inventory.HostHealth>;

export function CreateSession(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CreateSessionWithOptions(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string):Promise<void>;

export function CreateSessionWithOptionsV2(arg1:session.SessionLaunchRequest):Promise<void>;

export function DeleteCodexConfig(arg1:string):Promise<void>;

export function DeleteDockerConfig(arg1:string):Promise<void>;

export function DeleteHost(arg1:string):Promise<void>;

export function DeleteHostGroup(arg1:string):Promise<void>;

export function DeletePluginConfig(arg1:string):Promise<void>;

export function DeleteProfile(arg1:string):Promise<main.ProfileDeleteResult>;

export function DeleteScriptConfig(arg1:string):Promise<void>;

export function DeployIntegrationPluginWithOptions(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DetachSession(arg1:string):Promise<void>;

export function ExportBurrow():Promise<string>;

export function FocusBurrow(arg1:string):Promise<boolean>;

export function FocusDen(arg1:string):Promise<boolean>;

export function GetCodexConfigToml(arg1:string):Promise<string>;

export function GetDefaultTerminal():Promise<string>;

export function GetDenOrder(arg1:string):Promise<Array<string>>;

export function GetHostsHealth():Promise<Record<string, inventory.HostHealth>>;

export function GetInstalledTerminals():Promise<Array<terminal.TerminalApp>>;

export function GetInventory():Promise<inventory.Inventory>;

export function GetProviderPresets():Promise<Array<provider.Preset>>;

export function GetTmuxMouseEnabled():Promise<boolean>;

export function ImportBurrow(arg1:string):Promise<workspace.ImportResult>;

export function ImportSSHConfig(arg1:inventory.SSHConfigImportRequest):Promise<void>;

export function InstallIntegration(arg1:string):Promise<void>;

export function KillSession(arg1:string):Promise<void>;

export function ListCodexConfigs():Promise<Array<codex.Config>>;

export function ListDockerConfigs():Promise<Array<docker.Config>>;

export function ListIntegrationStatuses():Promise<Array<integration.IntegrationStatus>>;

export function ListLaunchPlugins():Promise<Array<session.PluginInfo>>;

export function ListPluginConfigs(arg1:string):Promise<Array<pluginconfig.Config>>;

export function ListProfiles():Promise<Array<profile.Profile>>;

export function ListScriptConfigs():Promise<Array<scriptcfg.Config>>;

export function ListSessions():Promise<Array<session.SessionStatus>>;

export function OpenDen(arg1:string):Promise<session.OpenDenResult>;

export function OpenIntegration(arg1:string):Promise<void>;

export function PickDirectory(arg1:string):Promise<string>;

export function PreviewSSHConfigImport(arg1:string):Promise<inventory.SSHConfigImportPreview>;

export function RemoveIntegrationPlugin(arg1:string):Promise<void>;

export function RestartSession(arg1:string):Promise<void>;

export function SaveCodexConfig(arg1:codex.SaveRequest):Promise<codex.Config>;

export function SaveDenOrder(arg1:string,arg2:Array<string>):Promise<void>;

export function SaveDockerConfig(arg1:docker.SaveRequest):Promise<docker.Config>;

export function SaveHost(arg1:inventory.Host):Promise<void>;

export function SaveHostGroup(arg1:inventory.HostGroup):Promise<void>;

export function SaveInventory(arg1:inventory.Inventory):Promise<void>;

export function SaveInventoryDefaults(arg1:inventory.HostDefaults):Promise<void>;

export function SavePluginConfig(arg1:pluginconfig.SaveRequest):Promise<pluginconfig.Config>;

export function SaveProfile(arg1:profile.Profile,arg2:Record<string, string>):Promise<void>;

export function SaveScriptConfig(arg1:scriptcfg.SaveRequest):Promise<scriptcfg.Config>;

export function SetDefaultTerminal(arg1:string):Promise<void>;

export function SetTmuxMouseEnabled(arg1:boolean):Promise<void>;

export function TestScriptCommand(arg1:string):Promise<scriptcfg.CommandTestResult>;

export function UpdateSession(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateSessionWithOptions(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string):Promise<void>;

export function UpdateSessionWithOptionsV2(arg1:session.SessionUpdateRequest):Promise<void>;

export function UploadFile(arg1:string,arg2:string):Promise<void>;
